//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyHelpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyHelpers.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day from now.
        /// </summary>
        internal static string DayFuture {
            get {
                return ResourceManager.GetString("DayFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        internal static string DayPast {
            get {
                return ResourceManager.GetString("DayPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days from now.
        /// </summary>
        internal static string DaysFuture {
            get {
                return ResourceManager.GetString("DaysFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string DaysPast {
            get {
                return ResourceManager.GetString("DaysPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muharram.
        /// </summary>
        internal static string HijriMonth1 {
            get {
                return ResourceManager.GetString("HijriMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shawwal.
        /// </summary>
        internal static string HijriMonth10 {
            get {
                return ResourceManager.GetString("HijriMonth10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhul Qadah.
        /// </summary>
        internal static string HijriMonth11 {
            get {
                return ResourceManager.GetString("HijriMonth11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhul Hijjah.
        /// </summary>
        internal static string HijriMonth12 {
            get {
                return ResourceManager.GetString("HijriMonth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safar.
        /// </summary>
        internal static string HijriMonth2 {
            get {
                return ResourceManager.GetString("HijriMonth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi Al-Awwal.
        /// </summary>
        internal static string HijriMonth3 {
            get {
                return ResourceManager.GetString("HijriMonth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi Al-Thani.
        /// </summary>
        internal static string HijriMonth4 {
            get {
                return ResourceManager.GetString("HijriMonth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada Al-Awwal.
        /// </summary>
        internal static string HijriMonth5 {
            get {
                return ResourceManager.GetString("HijriMonth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada Al-Thani.
        /// </summary>
        internal static string HijriMonth6 {
            get {
                return ResourceManager.GetString("HijriMonth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajab.
        /// </summary>
        internal static string HijriMonth7 {
            get {
                return ResourceManager.GetString("HijriMonth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaban.
        /// </summary>
        internal static string HijriMonth8 {
            get {
                return ResourceManager.GetString("HijriMonth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramadan.
        /// </summary>
        internal static string HijriMonth9 {
            get {
                return ResourceManager.GetString("HijriMonth9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hr from now.
        /// </summary>
        internal static string HourFuture {
            get {
                return ResourceManager.GetString("HourFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hr ago.
        /// </summary>
        internal static string HourPast {
            get {
                return ResourceManager.GetString("HourPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hr from now.
        /// </summary>
        internal static string HoursFuture {
            get {
                return ResourceManager.GetString("HoursFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hr ago.
        /// </summary>
        internal static string HoursPast {
            get {
                return ResourceManager.GetString("HoursPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a moment.
        /// </summary>
        internal static string InAMoment {
            get {
                return ResourceManager.GetString("InAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada Al-Akherah.
        /// </summary>
        internal static string Jumada2_AlAkherah {
            get {
                return ResourceManager.GetString("Jumada2_AlAkherah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada Al-Thaniyah.
        /// </summary>
        internal static string Jumada2_AlThaniyah {
            get {
                return ResourceManager.GetString("Jumada2_AlThaniyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min from now.
        /// </summary>
        internal static string MinuteFuture {
            get {
                return ResourceManager.GetString("MinuteFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min ago.
        /// </summary>
        internal static string MinutePast {
            get {
                return ResourceManager.GetString("MinutePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min from now.
        /// </summary>
        internal static string MinutesFuture {
            get {
                return ResourceManager.GetString("MinutesFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min ago.
        /// </summary>
        internal static string MinutesPast {
            get {
                return ResourceManager.GetString("MinutesPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mo from now.
        /// </summary>
        internal static string MonthsFuture {
            get {
                return ResourceManager.GetString("MonthsFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mo ago.
        /// </summary>
        internal static string MonthsPast {
            get {
                return ResourceManager.GetString("MonthsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s from now.
        /// </summary>
        internal static string SecondsFuture {
            get {
                return ResourceManager.GetString("SecondsFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s ago.
        /// </summary>
        internal static string SecondsPast {
            get {
                return ResourceManager.GetString("SecondsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wk from now.
        /// </summary>
        internal static string WeeksFuture {
            get {
                return ResourceManager.GetString("WeeksFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wk ago.
        /// </summary>
        internal static string WeeksPast {
            get {
                return ResourceManager.GetString("WeeksPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} yr from now.
        /// </summary>
        internal static string YearsFuture {
            get {
                return ResourceManager.GetString("YearsFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} yr ago.
        /// </summary>
        internal static string YearsPast {
            get {
                return ResourceManager.GetString("YearsPast", resourceCulture);
            }
        }
    }
}
