using System.Collections.Generic;

namespace SkyHelpers;

public class CountryInfo(string name, string code)
{
    public string Name { get; set; } = name;
    public string Code { get; set; } = code;
}

public static class PhoneCode
{
    public static List<CountryInfo> GetAll() => GetCountryPhoneCodes();

    public static List<CountryInfo> GetCountryPhoneCodes()
        {
        return
            [
                new("Afghanistan", "+93"),
                new("Albania", "+355"),
                new("Algeria", "+213"),
                new("Andorra", "+376"),
                new("Angola", "+244"),
                new("Antigua and Barbuda", "+1-268"),
                new("Argentina", "+54"),
                new("Armenia", "+374"),
                new("Australia", "+61"),
                new("Austria", "+43"),
                new("Azerbaijan", "+994"),
                new("Bahamas", "+1-242"),
                new("Bahrain", "+973"),
                new("Bangladesh", "+880"),
                new("Barbados", "+1-246"),
                new("Belarus", "+375"),
                new("Belgium", "+32"),
                new("Belize", "+501"),
                new("Benin", "+229"),
                new("Bhutan", "+975"),
                new("Bolivia", "+591"),
                new("Bosnia and Herzegovina", "+387"),
                new("Botswana", "+267"),
                new("Brazil", "+55"),
                new("Brunei", "+673"),
                new("Bulgaria", "+359"),
                new("Burkina Faso", "+226"),
                new("Burundi", "+257"),
                new("Cabo Verde", "+238"),
                new("Cambodia", "+855"),
                new("Cameroon", "+237"),
                new("Canada", "+1"),
                new("Central African Republic", "+236"),
                new("Chad", "+235"),
                new("Chile", "+56"),
                new("China", "+86"),
                new("Colombia", "+57"),
                new("Comoros", "+269"),
                new("Congo, Democratic Republic of the", "+243"),
                new("Congo, Republic of the", "+242"),
                new("Costa Rica", "+506"),
                new("Croatia", "+385"),
                new("Cuba", "+53"),
                new("Cyprus", "+357"),
                new("Czech Republic", "+420"),
                new("Denmark", "+45"),
                new("Djibouti", "+253"),
                new("Dominica", "+1-767"),
                new("Dominican Republic", "+1-809"), // and +1-829, +1-849
                new("East Timor (Timor-Leste)", "+670"),
                new("Ecuador", "+593"),
                new("Egypt", "+20"),
                new("El Salvador", "+503"),
                new("Equatorial Guinea", "+240"),
                new("Eritrea", "+291"),
                new("Estonia", "+372"),
                new("Eswatini", "+268"),
                new("Ethiopia", "+251"),
                new("Fiji", "+679"),
                new("Finland", "+358"),
                new("France", "+33"),
                new("Gabon", "+241"),
                new("Gambia", "+220"),
                new("Georgia", "+995"),
                new("Germany", "+49"),
                new("Ghana", "+233"),
                new("Greece", "+30"),
                new("Grenada", "+1-473"),
                new("Guatemala", "+502"),
                new("Guinea", "+224"),
                new("Guinea-Bissau", "+245"),
                new("Guyana", "+592"),
                new("Haiti", "+509"),
                new("Honduras", "+504"),
                new("Hungary", "+36"),
                new("Iceland", "+354"),
                new("India", "+91"),
                new("Indonesia", "+62"),
                new("Iran", "+98"),
                new("Iraq", "+964"),
                new("Ireland", "+353"),
                new("Italy", "+39"),
                new("Jamaica", "+1-876"),
                new("Japan", "+81"),
                new("Jordan", "+962"),
                new("Kazakhstan", "+7"),
                new("Kenya", "+254"),
                new("Kiribati", "+686"),
                new("Korea, North", "+850"),
                new("Korea, South", "+82"),
                new("Kosovo", "+383"),
                new("Kuwait", "+965"),
                new("Kyrgyzstan", "+996"),
                new("Laos", "+856"),
                new("Latvia", "+371"),
                new("Lebanon", "+961"),
                new("Lesotho", "+266"),
                new("Liberia", "+231"),
                new("Libya", "+218"),
                new("Liechtenstein", "+423"),
                new("Lithuania", "+370"),
                new("Luxembourg", "+352"),
                new("Madagascar", "+261"),
                new("Malawi", "+265"),
                new("Malaysia", "+60"),
                new("Maldives", "+960"),
                new("Mali", "+223"),
                new("Malta", "+356"),
                new("Marshall Islands", "+692"),
                new("Mauritania", "+222"),
                new("Mauritius", "+230"),
                new("Mexico", "+52"),
                new("Micronesia", "+691"),
                new("Moldova", "+373"),
                new("Monaco", "+377"),
                new("Mongolia", "+976"),
                new("Montenegro", "+382"),
                new("Morocco", "+212"),
                new("Mozambique", "+258"),
                new("Myanmar", "+95"),
                new("Namibia", "+264"),
                new("Nauru", "+674"),
                new("Nepal", "+977"),
                new("Netherlands", "+31"),
                new("New Zealand", "+64"),
                new("Nicaragua", "+505"),
                new("Niger", "+227"),
                new("Nigeria", "+234"),
                new("North Macedonia", "+389"),
                new("Norway", "+47"),
                new("Oman", "+968"),
                new("Pakistan", "+92"),
                new("Palau", "+680"),
                new("Palestine", "+970"),
                new("Panama", "+507"),
                new("Papua New Guinea", "+675"),
                new("Paraguay", "+595"),
                new("Peru", "+51"),
                new("Philippines", "+63"),
                new("Poland", "+48"),
                new("Portugal", "+351"),
                new("Qatar", "+974"),
                new("Romania", "+40"),
                new("Russia", "+7"),
                new("Rwanda", "+250"),
                new("Saint Kitts and Nevis", "+1-869"),
                new("Saint Lucia", "+1-758"),
                new("Saint Vincent and the Grenadines", "+1-784"),
                new("Samoa", "+685"),
                new("San Marino", "+378"),
                new("Sao Tome and Principe", "+239"),
                new("Saudi Arabia", "+966"),
                new("Senegal", "+221"),
                new("Serbia", "+381"),
                new("Seychelles", "+248"),
                new("Sierra Leone", "+232"),
                new("Singapore", "+65"),
                new("Slovakia", "+421"),
                new("Slovenia", "+386"),
                new("Solomon Islands", "+677"),
                new("Somalia", "+252"),
                new("South Africa", "+27"),
                new("South Sudan", "+211"),
                new("Spain", "+34"),
                new("Sri Lanka", "+94"),
                new("Sudan", "+249"),
                new("Suriname", "+597"),
                new("Sweden", "+46"),
                new("Switzerland", "+41"),
                new("Syria", "+963"),
                new("Taiwan", "+886"),
                new("Tajikistan", "+992"),
                new("Tanzania", "+255"),
                new("Thailand", "+66"),
                new("Togo", "+228"),
                new("Tonga", "+676"),
                new("Trinidad and Tobago", "+1-868"),
                new("Tunisia", "+216"),
                new("Turkey", "+90"),
                new("Turkmenistan", "+993"),
                new("Tuvalu", "+688"),
                new("Uganda", "+256"),
                new("Ukraine", "+380"),
                new("United Arab Emirates", "+971"),
                new("United Kingdom", "+44"),
                new("United States", "+1"),
                new("Uruguay", "+598"),
                new("Uzbekistan", "+998"),
                new("Vanuatu", "+678"),
                new("Vatican City", "+39"),
                new("Venezuela", "+58"),
                new("Vietnam", "+84"),
                new("Yemen", "+967"),
                new("Zambia", "+260"),
                new("Zimbabwe", "+263"),
            ];
    }
}